
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:F1TelemetryUi.ViewModels.MainViewModel.#ctor(Caliburn.Micro.IWindowManager,Caliburn.Micro.IEventAggregator,F1Telemetry.F1Manager,F1TelemetryUi.Referencing.ReferencingStateMachine)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:F1TelemetryUi.ViewModels.MainViewModel._f1Manager_NewLap(System.Object,F1Telemetry.NewLapEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:F1TelemetryUi.ViewModels.MainViewModel._f1Manager_PacketReceived(System.Object,F1Telemetry.PacketReceivedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:F1TelemetryUi.ViewModels.MapViewModel.MapClick(System.Windows.Input.MouseButtonEventArgs)")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~F:F1TelemetryUi.ValueConverters.TyreCompoundToImageConverter.s_hardImage")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~F:F1TelemetryUi.ValueConverters.TyreCompoundToImageConverter.s_hyperSoftImage")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~F:F1TelemetryUi.ValueConverters.TyreCompoundToImageConverter.s_intermediateImage")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~F:F1TelemetryUi.ValueConverters.TyreCompoundToImageConverter.s_mediumImage")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~F:F1TelemetryUi.ValueConverters.TyreCompoundToImageConverter.s_softImage")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~F:F1TelemetryUi.ValueConverters.TyreCompoundToImageConverter.s_superHardImage")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~F:F1TelemetryUi.ValueConverters.TyreCompoundToImageConverter.s_superSoftImage")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~F:F1TelemetryUi.ValueConverters.TyreCompoundToImageConverter.s_ultraSoftImage")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~F:F1TelemetryUi.ValueConverters.TyreCompoundToImageConverter.s_wetImage")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:F1TelemetryUi.ViewModels.MapViewModel.CreateSaveBitmap")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:F1TelemetryUi.ViewModels.MapViewModel.GetLatestData~System.Collections.Generic.List{F1Telemetry.Models.Raw.F12017.F12017TelemetryPacket}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:F1TelemetryUi.Views.MapView.GetLatestData~System.Collections.Generic.List{F1Telemetry.Models.Raw.F12017.F12017TelemetryPacket}")]
