namespace F1Telemetry.Models.Raw.F12018
{
    public enum Driver : byte
    {
        CarlosSainz = 0,
        DanielRicciardo = 2,
        FernandoAlonso = 3,
        KimiRaikkonen = 6,
        LewisHamilton = 7,
        MarcusEricsson = 8,
        MaxVerstappen = 9,
        NicoHulkenberg = 10,
        KevinMagnussen = 11,
        RomainGrosjean = 12,
        SebastianVettel = 13,
        SergioPerez = 14,
        ValtteriBottas = 15,
        EstebanOcon = 17,
        StoffelVandoorne = 18,
        LanceStroll = 19,
        ArronBarnes = 20,
        MartinGiles = 21,
        AlexMurray = 22,
        LucasRoth = 23,
        IgorCorreia = 24,
        SophieLevasseur = 25,
        JonasSchiffer = 26,
        AlainForest = 27,
        JayLetourneau = 28,
        EstoSaari = 29,
        YasarAtiyeh = 30,
        CallistoCalabresi = 31,
        NaotaIzum = 32,
        HowardClarke = 33,
        WilheimKaufmann = 34,
        MarieLaursen = 35,
        FlavioNieves = 36,
        PeterBeousov = 37,
        KlimekMichalski = 38,
        SantiagoMoreno = 39,
        BenjaminCoppens = 40,
        NoahVisser = 41,
        GertWaldmuller = 42,
        JulianQuesada = 43,
        DanielJones = 44,
        CharlesLeclerc = 58,
        PierreGasly = 59,
        BrendonHartley = 60,
        SergeySirotkin = 61,
        RubenMeijer = 69,
        RashidNair = 70,
        JackTremblay = 71
    }
}
